"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 35;
let altura = 1.75;
const nacionalidade = 'brasileira';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 5, 6, 9];
const lista = ['Rafael', true, 35];
let idadeDaAna = 25;
idadeDaAna = '25 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'Rafael';
let curso = 'front-end';
//curso = 10;
